FROM ubuntu:22.04 

ARG CODE_NAME
ARG VERSION
ARG TARGET
ARG REPO

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN sed -i -e 's%deb http://archive.ubuntu.com/ubuntu%deb http://ftp.riken.go.jp/Linux/ubuntu/%g' /etc/apt/sources.list
RUN apt update\
 && apt install -y --no-install-recommends \
 gnupg \
 python3 \
 python3-all-dev \
 wget \
 doxygen \
 graphviz \
 pkg-config \
 libssl-dev \
 build-essential \
 debhelper \
 devscripts \
 fakeroot

RUN wget --no-check-certificate https://openrtm.org/pub/openrtm.key -O /etc/apt/keyrings/openrtm.key \
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/openrtm.key] http://${REPO}/pub/Linux/ubuntu/ ${CODE_NAME} main" | tee /etc/apt/sources.list.d/openrtm.list > /dev/null \
 && apt update \
 && apt install -y --no-install-recommends \
 libomniorb4-dev \
 omniidl \
 omniorb-nameserver \
 omniidl-python3 \
 python3-omniorb-omg

COPY OpenRTM-aist-Python /root/OpenRTM-aist-Python
WORKDIR /root/OpenRTM-aist-Python
RUN python3 setup.py build \
 && python3 setup.py sdist \
 && mkdir -p /root/${TARGET}-src-pkgs \
 && cp dist/* /root/${TARGET}-src-pkgs/

WORKDIR /root/OpenRTM-aist-Python/dist
RUN mkdir -p /root/${TARGET}-deb-pkgs \
 && VERSION=`python3 ../setup.py --version` \
 && tar xf OpenRTM-aist-Python-${VERSION}.tar.gz \
 && cd OpenRTM-aist-Python-${VERSION}/packages \
 && make \
 && cp /root/OpenRTM-aist-Python/dist/OpenRTM-aist-Python-${VERSION}/packages/openrtm* /root/${TARGET}-deb-pkgs/
