FROM ubuntu:20.04

ARG TARGET

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN sed -i -e 's%deb http://archive.ubuntu.com/ubuntu%deb http://ftp.riken.go.jp/Linux/ubuntu/%g' /etc/apt/sources.list
RUN apt update\
 && apt install -y --no-install-recommends \
 build-essential \
 debhelper \
 devscripts \
 fakeroot \
 libsecret-1-0

COPY openrtp /root/openrtp
WORKDIR /root/openrtp/packages/deb
RUN sh dpkg_build.sh \
 && mkdir -p /root/${TARGET}-deb-pkgs \ 
 && cp /root/openrtp/packages/*.deb /root/${TARGET}-deb-pkgs/ 

