FROM ubuntu:18.04 

ARG VERSION="1.2.2"
ARG TARGET
ARG REPO

RUN sed -i -e 's%deb http://archive.ubuntu.com/ubuntu%deb http://ftp.riken.go.jp/Linux/ubuntu/%g' /etc/apt/sources.list
RUN apt update\
 && apt install -y --no-install-recommends \
 gnupg \
 autoconf \
 libtool \
 libtool-bin \
 gcc \
 g++ \
 cmake \
 make \
 python-yaml \
 uuid-dev \ 
 libboost-filesystem-dev \
 git \
 ca-certificates \
 wget \
 zip \ 
 unzip \ 
 python \
 doxygen \
 pkg-config \
 libssl-dev \
 build-essential \
 debhelper \
 devscripts \
 fakeroot

RUN wget -O- --no-check-certificate https://openrtm.org/pub/openrtm.key | apt-key add - \
 && echo "deb http://${REPO}/pub/Linux/ubuntu/ bionic main" >> /etc/apt/sources.list \
 && apt update \
 && apt install -y --no-install-recommends \
 libomniorb4-dev \
 omniidl \
 omniorb-nameserver \
 omniidl-python3 \
 python3-omniorb-omg

WORKDIR /root/tmp
RUN wget http://hp.vector.co.jp/authors/VA000501/qkcc100.zip \
 && unzip qkcc100.zip \
 && make \
 && cp qkc /usr/local/bin

COPY OpenRTM-aist /root/OpenRTM-aist
WORKDIR /root/OpenRTM-aist
RUN ./build/autogen \
 && ./configure --prefix=/usr --enable-fluentd=no \
 && make \
 && make dist \
 && mkdir -p /root/${TARGET}-src-pkgs \
 && cp OpenRTM-aist-${VERSION}.tar.* /root/${TARGET}-src-pkgs/ \
 && cp OpenRTM-aist-${VERSION}*.zip /root/${TARGET}-src-pkgs/

