FROM ubuntu:24.04 

ARG CODE_NAME
ARG VERSION
ARG JAVA_SHORT_VER
ARG TARGET
ARG REPO

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN sed -i -e 's%deb http://archive.ubuntu.com/ubuntu%deb http://ftp.riken.go.jp/Linux/ubuntu/%g' /etc/apt/sources.list
RUN apt update\
 && apt install -y --no-install-recommends \
 ant \
 junit \
 apt-transport-https \
 dirmngr \
 gnupg \
 software-properties-common \
 ca-certificates \
 wget \
 zip \ 
 unzip \ 
 cmake \
 doxygen \
 pkg-config \
 build-essential \
 debhelper \
 devscripts \
 fakeroot 

RUN wget --no-check-certificate https://openrtm.org/pub/openrtm.key -O /etc/apt/keyrings/openrtm.key \
 && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/openrtm.key] http://${REPO}/pub/Linux/ubuntu/ ${CODE_NAME} main" | tee /etc/apt/sources.list.d/openrtm.list > /dev/null \
 && apt update \
 && apt install -y --no-install-recommends \
 libomniorb4-dev \
 omniidl \
 omniorb-nameserver \
 omniidl-python3 \
 python3-omniorb-omg \
 openjdk-8-jdk \
 && JAVA8=`update-alternatives --list java | grep java-8` \
 && update-alternatives --set java ${JAVA8}

COPY OpenRTM-aist-Java /root/OpenRTM-aist-Java
WORKDIR /root/OpenRTM-aist-Java
RUN export JAVA_HOME=/usr/ \
 && sh buildRTC.sh \ 
 && sh buildPackage.sh

RUN mkdir -p /root/OpenRTM-aist-Java/work \
 && mkdir -p /root/${TARGET}-src-pkgs \
 && cp /root/OpenRTM-aist-Java/jp.go.aist.rtm.RTC/jar/source/OpenRTM*jar.zip /root/OpenRTM-aist-Java/work/ \
 && cp /root/OpenRTM-aist-Java/jp.go.aist.rtm.RTC/jar/source/OpenRTM*.zip /root/${TARGET}-src-pkgs/ \
 && cp /root/OpenRTM-aist-Java/jp.go.aist.rtm.RTC/jar/source/OpenRTM*.tar.gz /root/${TARGET}-src-pkgs/

WORKDIR /root/OpenRTM-aist-Java/work
RUN unzip OpenRTM-aist-Java-${VERSION}-jar.zip \
 && cd OpenRTM-aist/${JAVA_SHORT_VER} \
 && cp -r /root/OpenRTM-aist-Java/packages . \
 && cd packages/deb \
 && sh dpkg_build.sh

RUN mkdir -p /root/${TARGET}-deb-pkgs \
 && cp /root/OpenRTM-aist-Java/work/OpenRTM-aist/${JAVA_SHORT_VER}/packages/openrtm* /root/${TARGET}-deb-pkgs/
