FROM ubuntu:16.04 

ARG TARGET

RUN sed -i -e 's%deb http://archive.ubuntu.com/ubuntu%deb http://ftp.riken.go.jp/Linux/ubuntu/%g' /etc/apt/sources.list
RUN apt update\
 && apt install -y --no-install-recommends \
 build-essential \
 debhelper \
 devscripts \
 fakeroot 

COPY openrtp /root/openrtp
WORKDIR /root/openrtp/packages/deb
RUN sh dpkg_build.sh \
 && mkdir -p /root/${TARGET}-deb-pkgs \ 
 && cp /root/openrtp/packages/*.deb /root/${TARGET}-deb-pkgs/ 

